// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: server/proto/system.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockchainEvent struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Added         []*BlockchainEvent_Header `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	Removed       []*BlockchainEvent_Header `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockchainEvent) Reset() {
	*x = BlockchainEvent{}
	mi := &file_server_proto_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainEvent) ProtoMessage() {}

func (x *BlockchainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainEvent.ProtoReflect.Descriptor instead.
func (*BlockchainEvent) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{0}
}

func (x *BlockchainEvent) GetAdded() []*BlockchainEvent_Header {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *BlockchainEvent) GetRemoved() []*BlockchainEvent_Header {
	if x != nil {
		return x.Removed
	}
	return nil
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       int64                  `protobuf:"varint,1,opt,name=network,proto3" json:"network,omitempty"`
	Genesis       string                 `protobuf:"bytes,2,opt,name=genesis,proto3" json:"genesis,omitempty"`
	Current       *ServerStatus_Block    `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	P2PAddr       string                 `protobuf:"bytes,4,opt,name=p2pAddr,proto3" json:"p2pAddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_server_proto_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStatus) GetNetwork() int64 {
	if x != nil {
		return x.Network
	}
	return 0
}

func (x *ServerStatus) GetGenesis() string {
	if x != nil {
		return x.Genesis
	}
	return ""
}

func (x *ServerStatus) GetCurrent() *ServerStatus_Block {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *ServerStatus) GetP2PAddr() string {
	if x != nil {
		return x.P2PAddr
	}
	return ""
}

type Peer struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocols []string               `protobuf:"bytes,2,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Addrs     []string               `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// The peer's latest block, as this node last heard it over the sync protocol. Zero
	// when the peer has not announced one yet. The node already tracks this to decide who
	// to sync from; reporting it costs nothing and asks the peer for nothing.
	LatestBlock   uint64 `protobuf:"varint,4,opt,name=latest_block,json=latestBlock,proto3" json:"latest_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_server_proto_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{2}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Peer) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Peer) GetLatestBlock() uint64 {
	if x != nil {
		return x.LatestBlock
	}
	return 0
}

type PeersAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersAddRequest) Reset() {
	*x = PeersAddRequest{}
	mi := &file_server_proto_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersAddRequest) ProtoMessage() {}

func (x *PeersAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersAddRequest.ProtoReflect.Descriptor instead.
func (*PeersAddRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{3}
}

func (x *PeersAddRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PeersAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersAddResponse) Reset() {
	*x = PeersAddResponse{}
	mi := &file_server_proto_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersAddResponse) ProtoMessage() {}

func (x *PeersAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersAddResponse.ProtoReflect.Descriptor instead.
func (*PeersAddResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{4}
}

func (x *PeersAddResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PeersStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersStatusRequest) Reset() {
	*x = PeersStatusRequest{}
	mi := &file_server_proto_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersStatusRequest) ProtoMessage() {}

func (x *PeersStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersStatusRequest.ProtoReflect.Descriptor instead.
func (*PeersStatusRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{5}
}

func (x *PeersStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PeersListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersListResponse) Reset() {
	*x = PeersListResponse{}
	mi := &file_server_proto_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersListResponse) ProtoMessage() {}

func (x *PeersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersListResponse.ProtoReflect.Descriptor instead.
func (*PeersListResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{6}
}

func (x *PeersListResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type BlockByNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockByNumberRequest) Reset() {
	*x = BlockByNumberRequest{}
	mi := &file_server_proto_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockByNumberRequest) ProtoMessage() {}

func (x *BlockByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockByNumberRequest.ProtoReflect.Descriptor instead.
func (*BlockByNumberRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{7}
}

func (x *BlockByNumberRequest) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_server_proto_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{8}
}

func (x *BlockResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_server_proto_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{9}
}

func (x *ExportRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ExportRequest) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

type ExportEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// null when zero
	To            uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Latest        uint64 `protobuf:"varint,3,opt,name=latest,proto3" json:"latest,omitempty"`
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportEvent) Reset() {
	*x = ExportEvent{}
	mi := &file_server_proto_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEvent) ProtoMessage() {}

func (x *ExportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEvent.ProtoReflect.Descriptor instead.
func (*ExportEvent) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{10}
}

func (x *ExportEvent) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ExportEvent) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ExportEvent) GetLatest() uint64 {
	if x != nil {
		return x.Latest
	}
	return 0
}

func (x *ExportEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlockchainEvent_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockchainEvent_Header) Reset() {
	*x = BlockchainEvent_Header{}
	mi := &file_server_proto_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainEvent_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainEvent_Header) ProtoMessage() {}

func (x *BlockchainEvent_Header) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainEvent_Header.ProtoReflect.Descriptor instead.
func (*BlockchainEvent_Header) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BlockchainEvent_Header) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockchainEvent_Header) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ServerStatus_Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus_Block) Reset() {
	*x = ServerStatus_Block{}
	mi := &file_server_proto_system_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus_Block) ProtoMessage() {}

func (x *ServerStatus_Block) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_system_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus_Block.ProtoReflect.Descriptor instead.
func (*ServerStatus_Block) Descriptor() ([]byte, []int) {
	return file_server_proto_system_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServerStatus_Block) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ServerStatus_Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_server_proto_system_proto protoreflect.FileDescriptor

const file_server_proto_system_proto_rawDesc = "" +
	"\n" +
	"\x19server/proto/system.proto\x12\x02v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"\xaf\x01\n" +
	"\x0fBlockchainEvent\x120\n" +
	"\x05added\x18\x01 \x03(\v2\x1a.v1.BlockchainEvent.HeaderR\x05added\x124\n" +
	"\aremoved\x18\x02 \x03(\v2\x1a.v1.BlockchainEvent.HeaderR\aremoved\x1a4\n" +
	"\x06Header\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"\xc3\x01\n" +
	"\fServerStatus\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\x03R\anetwork\x12\x18\n" +
	"\agenesis\x18\x02 \x01(\tR\agenesis\x120\n" +
	"\acurrent\x18\x03 \x01(\v2\x16.v1.ServerStatus.BlockR\acurrent\x12\x18\n" +
	"\ap2pAddr\x18\x04 \x01(\tR\ap2pAddr\x1a3\n" +
	"\x05Block\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x03R\x06number\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"m\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tprotocols\x18\x02 \x03(\tR\tprotocols\x12\x14\n" +
	"\x05addrs\x18\x03 \x03(\tR\x05addrs\x12!\n" +
	"\flatest_block\x18\x04 \x01(\x04R\vlatestBlock\"S\n" +
	"\x0fPeersAddRequest\x12@\n" +
	"\x02id\x18\x01 \x01(\tB0\xfaB-r+2)^\\/[A-Za-z0-9._~-]+(\\/[A-Za-z0-9._~-]+)*$R\x02id\",\n" +
	"\x10PeersAddResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\">\n" +
	"\x12PeersStatusRequest\x12(\n" +
	"\x02id\x18\x01 \x01(\tB\x18\xfaB\x15r\x132\x11^[A-Za-z0-9]{1,}$R\x02id\"3\n" +
	"\x11PeersListResponse\x12\x1e\n" +
	"\x05peers\x18\x01 \x03(\v2\b.v1.PeerR\x05peers\".\n" +
	"\x14BlockByNumberRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"#\n" +
	"\rBlockResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"3\n" +
	"\rExportRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\"]\n" +
	"\vExportEvent\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\x12\x16\n" +
	"\x06latest\x18\x03 \x01(\x04R\x06latest\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data2\x8d\x03\n" +
	"\x06System\x125\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x10.v1.ServerStatus\x125\n" +
	"\bPeersAdd\x12\x13.v1.PeersAddRequest\x1a\x14.v1.PeersAddResponse\x12:\n" +
	"\tPeersList\x12\x16.google.protobuf.Empty\x1a\x15.v1.PeersListResponse\x12/\n" +
	"\vPeersStatus\x12\x16.v1.PeersStatusRequest\x1a\b.v1.Peer\x12:\n" +
	"\tSubscribe\x12\x16.google.protobuf.Empty\x1a\x13.v1.BlockchainEvent0\x01\x12<\n" +
	"\rBlockByNumber\x12\x18.v1.BlockByNumberRequest\x1a\x11.v1.BlockResponse\x12.\n" +
	"\x06Export\x12\x11.v1.ExportRequest\x1a\x0f.v1.ExportEvent0\x01B\x0fZ\r/server/protob\x06proto3"

var (
	file_server_proto_system_proto_rawDescOnce sync.Once
	file_server_proto_system_proto_rawDescData []byte
)

func file_server_proto_system_proto_rawDescGZIP() []byte {
	file_server_proto_system_proto_rawDescOnce.Do(func() {
		file_server_proto_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_system_proto_rawDesc), len(file_server_proto_system_proto_rawDesc)))
	})
	return file_server_proto_system_proto_rawDescData
}

var file_server_proto_system_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_proto_system_proto_goTypes = []any{
	(*BlockchainEvent)(nil),        // 0: v1.BlockchainEvent
	(*ServerStatus)(nil),           // 1: v1.ServerStatus
	(*Peer)(nil),                   // 2: v1.Peer
	(*PeersAddRequest)(nil),        // 3: v1.PeersAddRequest
	(*PeersAddResponse)(nil),       // 4: v1.PeersAddResponse
	(*PeersStatusRequest)(nil),     // 5: v1.PeersStatusRequest
	(*PeersListResponse)(nil),      // 6: v1.PeersListResponse
	(*BlockByNumberRequest)(nil),   // 7: v1.BlockByNumberRequest
	(*BlockResponse)(nil),          // 8: v1.BlockResponse
	(*ExportRequest)(nil),          // 9: v1.ExportRequest
	(*ExportEvent)(nil),            // 10: v1.ExportEvent
	(*BlockchainEvent_Header)(nil), // 11: v1.BlockchainEvent.Header
	(*ServerStatus_Block)(nil),     // 12: v1.ServerStatus.Block
	(*emptypb.Empty)(nil),          // 13: google.protobuf.Empty
}
var file_server_proto_system_proto_depIdxs = []int32{
	11, // 0: v1.BlockchainEvent.added:type_name -> v1.BlockchainEvent.Header
	11, // 1: v1.BlockchainEvent.removed:type_name -> v1.BlockchainEvent.Header
	12, // 2: v1.ServerStatus.current:type_name -> v1.ServerStatus.Block
	2,  // 3: v1.PeersListResponse.peers:type_name -> v1.Peer
	13, // 4: v1.System.GetStatus:input_type -> google.protobuf.Empty
	3,  // 5: v1.System.PeersAdd:input_type -> v1.PeersAddRequest
	13, // 6: v1.System.PeersList:input_type -> google.protobuf.Empty
	5,  // 7: v1.System.PeersStatus:input_type -> v1.PeersStatusRequest
	13, // 8: v1.System.Subscribe:input_type -> google.protobuf.Empty
	7,  // 9: v1.System.BlockByNumber:input_type -> v1.BlockByNumberRequest
	9,  // 10: v1.System.Export:input_type -> v1.ExportRequest
	1,  // 11: v1.System.GetStatus:output_type -> v1.ServerStatus
	4,  // 12: v1.System.PeersAdd:output_type -> v1.PeersAddResponse
	6,  // 13: v1.System.PeersList:output_type -> v1.PeersListResponse
	2,  // 14: v1.System.PeersStatus:output_type -> v1.Peer
	0,  // 15: v1.System.Subscribe:output_type -> v1.BlockchainEvent
	8,  // 16: v1.System.BlockByNumber:output_type -> v1.BlockResponse
	10, // 17: v1.System.Export:output_type -> v1.ExportEvent
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_server_proto_system_proto_init() }
func file_server_proto_system_proto_init() {
	if File_server_proto_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_system_proto_rawDesc), len(file_server_proto_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_system_proto_goTypes,
		DependencyIndexes: file_server_proto_system_proto_depIdxs,
		MessageInfos:      file_server_proto_system_proto_msgTypes,
	}.Build()
	File_server_proto_system_proto = out.File
	file_server_proto_system_proto_goTypes = nil
	file_server_proto_system_proto_depIdxs = nil
}
